### ISSUE TITLE
Zephyr 4.1 build fails with multiple errors

### ISSUE THREAD

**Issue by mike1808** [carrefinho/prospector-zmk-module#20]
# Description

When trying to compile the firmware with the prospector module the build fails with multiple errors:

**Error 1**

```
~/path/zmk-config/modules/prospector-zmk-module/boards/shields/prospector_adapter/src/layouts/field/output.c:120:49: warning: implicit declaration of function 'zmk_endpoints_selected'; did you mean 'zmk_endpoint_get_selected'? [-Wimplicit-function-declaration]
  120 |         struct zmk_endpoint_instance selected = zmk_endpoints_selected();
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~
      |                                                 zmk_endpoint_get_selected
~/path/zmk-config/modules/prospector-zmk-module/boards/shields/prospector_adapter/src/layouts/field/output.c:120:49: error: invalid initializer
```

Broke due to https://github.com/zmkfirmware/zmk/pull/3140. This is an easy fix, just rename `zmk_endpoints_selected` to `zmk_endpoint_get_selected`.

**Error 2**

```
zmk-config/modules/prospector-zmk-module/boards/shields/prospector_adapter/src/layouts/field/battery_label.c:15:31: error: 'ZMK_SPLIT_BLE_PERIPHERAL_COUNT' undeclared here (not in a function)
   15 | static uint8_t battery_levels[ZMK_SPLIT_BLE_PERIPHERAL_COUNT];
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Broke due to https://github.com/zmkfirmware/zmk/pull/3145. No idea how to fix this one. 

# Mitigation

For now, if you want to compile point your zmk to `ac7f75b8591d39aaf3b66b9d26f26c9ed921a009`

**Comment by rafiks** [comment]
i can confirm that this works for me as well
